server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.177.129
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        heartbeat:
          enabled: true

